# Generated by Django 3.2.7 on 2021-10-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('vote_cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('total_vote_cnt', models.IntegerField(default=0)),
                ('pop_time', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
